name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gdal
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - jupyterlab
  - beautifulsoup4
  - networkx
  - pillow
  - httpx
  - pyproj
  - hyperopt
  - imbalanced-learn
  - ipykernel
  - click
  - pyyaml
  - jinja2
  - pip
  - pip:
    - arrow
    - py4j
    - argon2-cffi
    - fqdn
    - pyobjc-core
    - pyobjc-framework-Cocoa